_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - google_analytics.settings
  - mobile_app_links.android
  - mobile_app_links.ios
  - pb_custom_form.language_redirects
  - pb_custom_form.mobile_app_share_link_form
  - smtp.settings
  - tmgmt.translator.memsource
